<%@ Control Language="C#" AutoEventWireup="true" CodeFile="TreeViewPerfil.ascx.cs" Inherits="Controles_TreeViewPerfil" %>
<sgr:treeview id="trvPerfil" runat="server" BorderStyle="None" ShowCheckBoxes="All" ShowExpandCollapse="False" Width="100%" AutoGenerateDataBindings="False" EnableClientScript="False">
    <NodeStyle ChildNodesPadding="1px" />
</sgr:treeview>
